# Dependencies
markdown:         redcarpet
highlighter:      rouge
theme:            jekyll-theme-minimal

# Permalinks
permalink:        pretty

# Setup
title:            tatatee.github.io
tagline:          ''
description:      ''
baseurl:          /

paginate:         5

